server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/level1?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: user
    password: 123456
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 1GB
      max-request-size: 2GB